name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Foundry Tests & Gas Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge tests
        run: forge test -vvv

      - name: Check Gas Snapshot
        run: forge snapshot --check
